/* 
 * Copyright (C) 2017 Petr Ryšavý <petr.rysavy@fel.cvut.cz>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.cvut.fel.ida.reads.readsIDA2017.contigdist;

import cz.cvut.fel.ida.reads.readsIDA2016.dist.EditDistance;
import cz.cvut.fel.ida.reads.readsIDA2016.model.Sequence;
import java.util.Arrays;
import java.util.Collection;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;

import static org.hamcrest.CoreMatchers.equalTo;
import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.*;

/**
 * Test for Algorithm 1 from IDA 2017 paper.
 * 
 * @author Petr Ryšavý
 */
@RunWith(Parameterized.class)
public class OverlapFinderTest {

    private static final String S1 = "TTTGGTCGCTGTCTGGCTGTCAGTAAGTATGCTAGAGTCCCGTTTCCGTTTCATTACCAACACCACGTCTCCTTGCCCAATTAGCACATTAGCCTTCTCTCCTTTCGCAAGGTTGCTCAGTTCATTGATGCTTAGTGCTGGCCCATATCTCTTGTCTTCTTTGCCCAGAATGAGGAATCCCCTCAGAACAGCGGACTCCACTCCAGCTGTGCCTTCATCTGGGTCTTCAGTTAAAGTGCCAGCATCCTTTCCGAGAACTGTGAGTCTCTTCGTGGCCTTGTTATAGTTGAATACAGGAGAATTGCCCCTTACAAGTATTCTCATTCCTGATCCCCTCACATTCACAGTAAATGAGGAGAACTGCATTCTACTTTGCTTTGGTGGAGCGGCTGCGAAGGGAAGAAGTTTTATTATCTGTGCGGTATCAAATGTCCCAAGCACATCCCTCATTTGTTGGAACAGAGTTCTTACAAACCCACTGTATTGGCCTCTAATGGCCTTAGGTACTAAAGACTGAAATGGTTCAAATTCCATTTTATTGTATAGCATTGTAGGGTTCTGGGACCACTGAATTTTAACAGTTTCCCAGTTTCTGATGATCCATTGATAGGTATTGACCAACACTGATTCAGGACCATTAATCTCCCACATCATTGACGATGAGTAAGTTATTGTCAGTTTCTCTGTTCCCTGTGTTTCACTGACCTCCTCGGGAGACAGTAGTACATTTCCTCGTTGGTCCCGGATTCTCAAAAAACGGTCAATGCTCACCACTACCCTCTCCGTGCTGGAGTACTCATCTACACCCATTTTGCTGATTCTCACTCCTCTCATTGACATCTCGATGCTTGGAGTCATGTCTGGCAATATCCCAATCATTCCCATCACATTGTCGATAGGTTCAACTCCCCAATTTTGAAAAAGCACTTTCGCATCCTTCTGAAAATGTCTTAAAAGTTGATGCATAGGATTCAATCGCTGATTCGCCCTATTGACGAAATTCAGATCACCTCTGACTGCTTTTATCATACAATCCTCTTGTGAAAATACCATGGCCACAATTATTGCTTCGGCAATCGACTGTTCGTCTCTCCCACTCACTATCAGCTGAATCAATCTCCTGGTTGCTTTTCTGAGTATGGCTGTTGCTCTTCTCCCAACCATTGTGAACTCTTCATATCCCTCATGCACTCTTATCTTCAATGTTTGAAGATTGCCCGTAAGCACCTCTTCCTCTCTCTTGACTGATGATCCGCTTGTTCTCTTAAATGTGAATCCACCAAAACTGAAGGATGAGCTAATTCTCAGTCCCATTGCAGCCTTGCATATATCCACGGCTTGCTCTTCTGTTGGGTTCTGCCTAAGGATGTCTACCATCCTAATTCCACCAATCTGTGTGCTGTGGCACATCTCCAATAAAGATGCTAGTGGATCTGCTGATACTGCAGCTCTTCTCACTATGTTCCTAGCAGCAATAATCAAGCTTTGATCAACATCATCATTCCTCACTTCCCCTCCTGGAGTATACATCTGTTCCCAGCATGTTCCTTGAGTCAAATGCAACACTTCAATGTACACACTGCTTGTTCCACCAGCCACTGGGAGGAATCTCGTTTTGCGGACCAGTTCTCTCTCCAACATGTATGCAACCATCAAAGGAGAAATTTTGCAATCCTGGAGTTCTTCTTTCTTCTCTTTGGTTATCGTTAGTTGCGATTCCGATGTTAGTATCCTGGCTCCCACTTCGTTAGGGAAAACAACTTCCATGATTACATCCTGTGCCTCCTTGGCACTGAGATCTGCATGACCAGGATTTATGTCAACTCTCCGACGTATTTTGACTTGGTTTCTAAAATGGACAGGGCCAAAGGTTCCATGCTTTAGCCTTTCGACTCTTTCAAAATAAGTTTTGTAGATTTTTGGATAATGAACTGTATTTGTTATTGGTCCATTCCTATTCCACCATGTCACAGCCAGAGGTGATACCATCACTCGGTCTGATCCTGCATCATTCATTTTACTCCATAAAGTTTGTCCTTGCTCATTTCTCTCAGGAATCATTTCCGTTATCCTCTTGTCTGCTGTAATTGGATATTTCATTGCCATCATCCATTTCATCCTAAGTGCTGGGTTCTTCTCCTGTCTTCCTGATGTGTACTTCTTGATTATGGC";
    private static final String S2 = "GACGTAACAGAGGCTTCTTTATTCTAGGAAGTAATGAGTACAGTTTCCTTCCGTGCTAGCCCGAGCGACGGAAAAGCAGGCTCTCGAGCTTCTGAGGGGCGGGGACCTTTCTGTGTAGAAGACCAGAACGTGAAAGGTAGTAGGAATACTAAAGCCAGGAGTACAGTCTACAAGAAGGGAGACATAAGGGTAACTTACGACGGTATTACCAACAAGACAGTTTTCCCTCTAAAGAGACATGACTCTTGCATCCAACATACGACTAAACCGGGCGTCTACGGGAGACAACTAACCACAAAGGAGGTGAAGACCAGGAATACCGGGTCATGGACGAAGAGTCAAGTTCACATGAACTAAGGTATCAGAGGTATAAAAGTAACCTTCGTTAAACTTGAGGAGATCACCTTTCGAAGGGAGAACCCTCGTGGAAGCAGGGAAACTACTTCGAATTATGAGAATCTAGAAGTTTACGCCGTCTTACCGTACGGTAGGTGTGGTCAACTGAGAACACACGACCTAAGAGTAAACCAGACTAATCCGACATGTGAACCGACAAAACTTCGTCAGACTTTCCCAGATAAGGCTGATCTCTCATAGGGAGAGAAAGTTTCAGCATGGGTGACCGATGCCGTCCAGGTATGTGTGTCCGTCCGTCCGTCCTGAACACTCGTTGGCTGGGAGAGTTATACTCACGTCTGGCACGATCTTTTCACTCTAGAAGCTTGAGTCGTAAGGGACCCAAGGCCGAGAGAGAGTGAACTAGGTAGTAACGAAAAACACGTCGTCAAACTTTAAAGGGAAACTCTTACAACGTGTAAGAAAGTATTCGTTAAGAACAAAAAGCAGGTAAGAGTGGGGAGGTCTTCAAGGCTAGTAACTAGGGTGCAAACTAGTAGGACTGGTTAAGGTAGTGGTAACAAGGTTGAGGAAACTGACGTCGTGGACGCCGAGGTCTGGAGGATCCCTCTCAACTTGGAACGTAGTCTCTCGTGTAGGACCCTAGGTAAGGCCACGCTTGTTCTCGAGAACAGGAGACTATTCAACGTAGTAAGTTTAACCTTACGGTCTAGTAGTACACTCAGTCTGGTCGGCAACGTAGCAGTGGTAATAATCGAACCGCGGTCTAAGCGGAATAAAGAAGAAACAGTATTTCCTACTCAAGAGAGTAGGTGAAAGGCAAATGAGAGGACATATATCCAGGAGGTCAAAAGAATCCTAGAAAGGGGCGTGACCCTACAAGAAGGTCCATAAATAAAGAGGAAAGCAGTTTTCGTCTCTCGTGGTAAGAGAGATAACAATTCGACAAAACCTAGTTGGCAGGGAGTATTAGTGACTCAAACTCAAGCCACGTGTAAACCTACATCTTAGCAGGTTAAGGTGGTTAGTAAAAAGGCTGCCTACGAGACTAAAGTCACCGTAAGACCGCAAGAGGTAGTCAGAGGTAGACAAGCAT";

    @Parameterized.Parameters
    public static Collection<Object[]> data() {
        return Arrays.asList(new Object[][]{
            {"CATG", "AAGC", 1, 4, 0, 3, 1, 2},
            {"ABCDEF", "DEFGHI", 3, 6, 0, 3, 0, 2},
            {"ABCDEFGH", "DEFGHI", 3, 8, 0, 5, 0, 2},
            {"ABCDEF", "XYZABC", 0, 3, 3, 6, 0, 2},
            {"ABCDEFGH", "XYZABCDEF", 0, 6, 3, 9, 0, 2},
            {"ABCDEF", "DXFGHI", 3, 6, 0, 3, 1, 2},
            {"ABCDEFGH", "DEXGHI", 3, 8, 0, 5, 1, 2},
            {"AMCDEF", "XYZABC", 0, 3, 3, 6, 1, 2},
            {"ABMDEFGH", "XYZABCDEF", 0, 6, 3, 9, 1, 2},
            {"ABCDEF", "DXFGHI", 3, 6, 0, 3, 1, 2},
            {"ABCDEYXH", "DEFGHI", 3, 8, 0, 5, 2, 2},
            {"ABCDEFGHIJKL", "DEFGH", 3, 8, 0, 5, 0, 2},
//            {"ABCYEFGXIJKL", "DEFGH", 3, 7, 0, 5, 2, 2},
            {"DEFGH", "ABCDEFGHIJKL", 0, 5, 3, 8, 0, 2},
//            {"DEFGH", "ABCYEFGXIJKL", 0, 5, 4, 8, 5, 2},
            {"GACGTAACAGAGGCTTCTTTATTCTAGGAXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYGATGTGTACTTCTTGATTATGGC", 0, 29, 32, 32 + 23, 12, 10},
            {S1, S2, 2141, 2172, 0, 27, 13, 10}
        });
    }

    private final Sequence pattern, query;
    private final int startA, endA, startB, endB;
    private final double distance;
    private final int threshold;

    public OverlapFinderTest(String pattern, String query, int startA, int endA, int startB, int endB, int distance, int threshold) {
        this.pattern = Sequence.fromString(pattern);
        this.query = Sequence.fromString(query);
        this.startA = startA;
        this.endA = endA;
        this.startB = startB;
        this.endB = endB;
        this.distance = distance;
        this.threshold = threshold;
    }

    @Test
    public void testGetOverlap() {
        final OverlapRegion result = new OverlapFinder(threshold).getOverlap(pattern, query);
        System.err.println("pattern : " + pattern + " query " + query);
        System.err.println("result : " + result + ", " + result.distanceToLengthRatio());
        assertThat(result.getStartA(), is(equalTo(startA)));
        assertThat(result.getEndA(), is(equalTo(endA)));
        assertThat(result.getStartB(), is(equalTo(startB)));
        assertThat(result.getEndB(), is(equalTo(endB)));
        assertThat(result.getDistance(), is(equalTo(distance)));
        assertThat(result.getDistance(), is(equalTo(
                new EditDistance().getDistance(pattern.subSequence(startA, endA), query.subSequence(startB, endB)))));
        System.err.println("ok");
    }

    @Test
    public void testGetOverlapSym() {
        final OverlapRegion result = new OverlapFinder(threshold).getOverlap(query, pattern);
        System.err.println("query : " + query + "\npattern " + pattern);
        System.err.println("result : " + result + ", " + result.distanceToLengthRatio());
        assertThat(result.getStartA(), is(equalTo(startB)));
        assertThat(result.getEndA(), is(equalTo(endB)));
        assertThat(result.getStartB(), is(equalTo(startA)));
        assertThat(result.getEndB(), is(equalTo(endA)));
        assertThat(result.getDistance(), is(equalTo(distance)));
        assertThat(result.getDistance(), is(equalTo(
                new EditDistance().getDistance(pattern.subSequence(startA, endA), query.subSequence(startB, endB)))));
        System.err.println("ok");
    }

}
